# index:
#     path: /
#     controller: App\Controller\homeController::index

app_cgv:
    path: /cgv
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'statique/cgv.html.twig'